name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Node 14 
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Update npm version to latest
      run: npm install -g npm@latest # shop showing warnings about the lockfile
    - name: Install dependencies
      run: npm install
    - name: Compile
      run: npm run build
