name: build

on: [push, pull_request]

jobs:
  build:
    name: Build on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        node: [ 20, 22, 24 ]

    steps:
    - uses: actions/checkout@v5
    - name: Using Node ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Update npm version to latest
      run: npm install -g npm@latest # shop showing warnings about the lockfile
    - name: Install dependencies
      run: npm install
    - name: Compile
      run: npm run build
